logging:
  level:
    root: WARN

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always

server:
  address: 0.0.0.0

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

user:
  email: 'hexlet@example.com'
  password: 'qwerty'