name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Generate RSA Key Pair with OpenSSL
        run: |
          echo "Generating certs..."
          mkdir src/main/resources/certs
          openssl genrsa -out src/main/resources/certs/private.pem 2048
          openssl rsa -in src/main/resources/certs/private.pem -outform PEM -pubout -out src/main/resources/certs/public.pem

      - name: Building
        run: ./gradlew build
      - uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml